version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=chichen_itza_db
      - FRONTEND_PATH=/frontend
    volumes:
      - ./backend:/usr/src/app
      - ./frontend:/frontend
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - tour-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chichen_itza_db
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - tour-network

networks:
  tour-network:
    driver: bridge

volumes:
  mysql-data:
